server:
  port: 80
  servlet:
    #项目的上下文路径
    context-path: /
#连接池
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/bill
  thymeleaf:
    #关闭thymeleaf缓存
    cache: false
#整合mybatis
mybatis:
  #别名搜索
  type-aliases-package: com.lql.bill.entity
  mapper-locations: classpath:/mybatis/*.xml
